# Health Check
GET http://localhost:8080/

###

# Transaction Sale
POST http://localhost:8081/api/transactions/sale
Content-Type: application/json

{
    "merchant_id": "MCH123",
    "terminal_id": "T01",
    "amount": 125000,
    "card_number": "411111******1111",
    "timestamp": "2025-10-05T12:45:00Z"
}

###

# Transaction Settlement
POST http://localhost:8080/api/transactions/settlement
Content-Type: application/json

{
  "transaction_id": "the_transaction_id_from_sale_response"
}

###

# core-service
POST http://localhost:9000/core/authorize
Content-Type: application/json
X-Service-Token: servicesecret

{
  "merchant_id": "M001",
  "terminal_id": "T001",
  "amount": 2000,
  "card_number": "1234567890123456",
  "timestamp": "2025-10-06T12:30:00Z"
}