// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"bri-edc/api/config"
	"bri-edc/api/internal/handler"
	"bri-edc/api/internal/repositories"
	"bri-edc/api/internal/services"
	"gorm.io/gorm"
)

// Injectors from app_injector.go:

func InitializeApp() (*AppContainer, error) {
	db := config.ConnectGormDB()
	authRepository := repositories.NewAuthRepository()
	authService := services.NewAuthService(db, authRepository)
	authHandler := handler.NewAuthHandler(authService)
	transactionRepository := repositories.NewTransactionRepository()
	merchantRepository := repositories.NewMerchantRepository()
	terminalRepository := repositories.NewTerminalRepository()
	settlementRepository := repositories.NewSettlementRepository()
	transactionService := services.NewTransactionService(db, transactionRepository, merchantRepository, terminalRepository, settlementRepository)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	appContainer, err := NewAppContainer(db, authHandler, transactionHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}

// app_injector.go:

type AppContainer struct {
	DB *gorm.DB
	//
	AuthHandler        *handler.AuthHandler
	TransactionHandler *handler.TransactionHandler
}

func NewAppContainer(
	db *gorm.DB,

	authHandler *handler.AuthHandler,
	transactionHandler *handler.TransactionHandler,
) (*AppContainer, error) {
	return &AppContainer{
		DB: db,

		AuthHandler:        authHandler,
		TransactionHandler: transactionHandler,
	}, nil
}
